/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicApp;

import javax.swing.JOptionPane;

/**
 *
 * @author Laili
 */
public class beranda extends javax.swing.JFrame {

    /**
     * Creates new form beranda
     */
    public beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        butDaftarpasien = new javax.swing.JButton();
        butHasilpasien = new javax.swing.JButton();
        buutDataobat = new javax.swing.JButton();
        butKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        butRiwayatpasien = new javax.swing.JButton();
        butDokter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Klinik  Helgi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        butDaftarpasien.setBackground(new java.awt.Color(255, 255, 255));
        butDaftarpasien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butDaftarpasien.setText("Pendaftaran Pasien Baru");
        butDaftarpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDaftarpasienActionPerformed(evt);
            }
        });
        jPanel1.add(butDaftarpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        butHasilpasien.setBackground(new java.awt.Color(255, 255, 255));
        butHasilpasien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butHasilpasien.setText("Hasil Periksa Pasien");
        butHasilpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHasilpasienActionPerformed(evt);
            }
        });
        jPanel1.add(butHasilpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        buutDataobat.setBackground(new java.awt.Color(255, 255, 255));
        buutDataobat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buutDataobat.setText("Bank Obat");
        buutDataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buutDataobatActionPerformed(evt);
            }
        });
        jPanel1.add(buutDataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        butKeluar.setBackground(new java.awt.Color(255, 255, 255));
        butKeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/out.png"))); // NOI18N
        butKeluar.setText(" Keluar");
        butKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(butKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1120, 10));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Pilih Salah Satu Menu Untuk Memulai");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        butRiwayatpasien.setBackground(new java.awt.Color(255, 255, 255));
        butRiwayatpasien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butRiwayatpasien.setText("Riwayat Pasien");
        butRiwayatpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRiwayatpasienActionPerformed(evt);
            }
        });
        jPanel1.add(butRiwayatpasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, -1, -1));

        butDokter.setBackground(new java.awt.Color(255, 255, 255));
        butDokter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butDokter.setText("Data Dokter");
        butDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDokterActionPerformed(evt);
            }
        });
        jPanel1.add(butDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modern Healthcare Clinic Logodj.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, 100));

        jLabel3.setFont(new java.awt.Font("Cambria", 2, 16)); // NOI18N
        jLabel3.setText("Mitra Pelayanan Kesehatan Yang Menjamin Kepuasan Pasien");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 10));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 290, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/pendaftaran.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/hasil periksa.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/riwayat.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, -1, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dokterr.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/obatt.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 2, 1120, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDaftarpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDaftarpasienActionPerformed
        // TODO add your handling code here:
        new pasien().show();
            this.dispose();
    }//GEN-LAST:event_butDaftarpasienActionPerformed

    private void butKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKeluarActionPerformed
       if(JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar aplikasi?", "Keluar",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
           System.exit(0); 
        }
    }//GEN-LAST:event_butKeluarActionPerformed

    private void butHasilpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHasilpasienActionPerformed
        // TODO add your handling code here:
        new checkup().show();
            this.dispose();
    }//GEN-LAST:event_butHasilpasienActionPerformed

    private void buutDataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buutDataobatActionPerformed
        new bankobat().show();
            this.dispose();
    }//GEN-LAST:event_buutDataobatActionPerformed

    private void butRiwayatpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRiwayatpasienActionPerformed
        new riwayatpasien().show();
            this.dispose();
    }//GEN-LAST:event_butRiwayatpasienActionPerformed

    private void butDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDokterActionPerformed
        new daftardokter().show();
            this.dispose();
    }//GEN-LAST:event_butDokterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butDaftarpasien;
    private javax.swing.JButton butDokter;
    private javax.swing.JButton butHasilpasien;
    private javax.swing.JButton butKeluar;
    private javax.swing.JButton butRiwayatpasien;
    private javax.swing.JButton buutDataobat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
