package clinicApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class daftardokter extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private ResultSet RsDokter;
    private String sql="";

    private String poli, nama, nohp, alamat, jasa;

    /**
     * Creates new form daftardokter
     */
    public daftardokter() {
        initComponents();
        kontabel();
        showdata("SELECT * FROM tabel_dokter");
    }
    
    private void form_awal(){
        form_disable();
        form_clear(); 
        butSimpan.setText("Simpan");
        butTambah.requestFocus(true);
        butTambah.setEnabled(true);
        butSimpan.setEnabled(false);
        butHapus.setEnabled(false); 
    }
    
    private void form_disable(){
        cmbPoli.setEnabled(false);
        txtNama.setEnabled(false);
        txtAlamat.setEnabled(false);
        txtJasa.setEnabled(false);
        txtHp.setEnabled(false);
       }
  
    private void form_enable(){
        cmbPoli.setEnabled(true);
        txtNama.setEnabled(true);
        txtAlamat.setEnabled(true);
        txtHp.setEnabled(true);
        txtJasa.setEnabled(true);
        }
  
    private void form_clear(){
        cmbPoli.setSelectedItem("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtHp.setText("");
        txtJasa.setText("");
         }
    
    private void kontabel (){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_klinikhelgi", "root", "");  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "GAGAL Terkoneksi Dengan Database \n");
        }
    }
    
    private void showdata (String sql){
        DefaultTableModel datalist = new DefaultTableModel();;
        datalist.addColumn("Poli");
        datalist.addColumn("Nama Dokter");
        datalist.addColumn("Alamat Dokter");
        datalist.addColumn("No. HP");
        datalist.addColumn("Jasa Dokter");
        try {
            st=con.createStatement();
            RsDokter=st.executeQuery("SELECT * FROM tabel_dokter");
            while (RsDokter.next()){
                datalist.addRow(new Object[]{
                    RsDokter.getString(1), RsDokter.getString(2),RsDokter.getString(3), 
                    RsDokter.getString(4), RsDokter.getString(5)
                });
                gridDokter.setModel(datalist);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL DITAMPILKAN\n"+e.getMessage());
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridDokter = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        butSimpan = new javax.swing.JButton();
        butHapus = new javax.swing.JButton();
        butTambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtJasa = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtHp = new javax.swing.JTextField();
        cmbPoli = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modern Healthcare Clinic Logodj.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Klinik Helgi");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jLabel3.setText("Mitra Pelayanan Kesehatan Yang Menjamin Kepuasan Pasien");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        butKembali.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        butKembali.setText(" Kembali");
        butKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKembaliActionPerformed(evt);
            }
        });
        jPanel3.add(butKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1120, 100));

        gridDokter.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gridDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Poli", "Nama Dokter", "Alamat", "No. Hp", "Jasa Dokter"
            }
        ));
        gridDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridDokterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridDokter);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 560, 280));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Daftar Dokter Klinik Helgi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 260, 10));

        butSimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        butSimpan.setText(" Simpan");
        butSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(butSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 270, -1));

        butHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        butHapus.setText(" Hapus");
        butHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHapusActionPerformed(evt);
            }
        });
        jPanel1.add(butHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 270, -1));

        butTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        butTambah.setText(" Tambah");
        butTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTambahActionPerformed(evt);
            }
        });
        jPanel1.add(butTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 270, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Jasa Dokter");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Poli");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Nama Dokter");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Alamat");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("No. Hp");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        txtJasa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtJasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 260, -1));

        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 260, -1));

        txtAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 260, -1));

        txtHp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 260, -1));

        cmbPoli.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbPoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Umum", "Gigi" }));
        jPanel1.add(cmbPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1120, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKembaliActionPerformed
        new beranda().show();
            this.dispose();
    }//GEN-LAST:event_butKembaliActionPerformed

    private void butSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSimpanActionPerformed
        poli=cmbPoli.getItemAt(cmbPoli.getSelectedIndex()).toString();;
        nama=String.valueOf(txtNama.getText());
        alamat=String.valueOf(txtAlamat.getText());
        nohp=String.valueOf(txtHp.getText());
        jasa=String.valueOf(txtJasa.getText());
        try {
            sql="INSERT INTO tabel_dokter(nama_poli, "
            + "nama_dokter, "
            + "alamat_dokter, "
            + "no_hp, "
            + "jasa_dokter)VALUES"
            + "('"+ poli +"',"
            + "'"+ nama +"',"
            + "'"+ alamat +"',"
            + "'"+ nohp +"',"
            + "'"+ jasa +"')";
            st=con.createStatement();
            st.execute(sql);
            showdata("SELECT * FROM tabel_dokter");
            form_awal();
            JOptionPane.showMessageDialog(null, "Data Dokter BERHASIL DISIMPAN");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Dokter GAGAL DISIMPAN \n"+e.getMessage());
        }
    }//GEN-LAST:event_butSimpanActionPerformed

    private void butHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHapusActionPerformed
        nama = String.valueOf(txtNama.getText());
      
        try {
            sql= "DELETE FROM tabel_dokter WHERE tabel_dokter.nama_dokter =  '"+nama+"'";
            st=con.createStatement();
            st.execute(sql);
            showdata("SELECT * FROM tabel_dokter");
            form_awal();
            JOptionPane.showMessageDialog(null, "Data Dokter BERHASIL DIHAPUS");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Dokter GAGAL DIHAPUS \n"+e.getMessage());
        }
    }//GEN-LAST:event_butHapusActionPerformed

    private void butTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTambahActionPerformed
        form_enable();
        butTambah.setEnabled(true);
        butSimpan.setEnabled(true);
        butHapus.setEnabled(true);
    }//GEN-LAST:event_butTambahActionPerformed

    private void gridDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridDokterMouseClicked
        if (gridDokter.getSelectedRowCount()>-1)
        {
            cmbPoli.setSelectedItem(gridDokter.getValueAt(gridDokter.getSelectedRow(), 0).toString());
            txtNama.setText(gridDokter.getValueAt(gridDokter.getSelectedRow(), 1).toString());
            txtAlamat.setText(gridDokter.getValueAt(gridDokter.getSelectedRow(), 2).toString());
            txtHp.setText(gridDokter.getValueAt(gridDokter.getSelectedRow(), 3).toString());
            txtJasa.setText(gridDokter.getValueAt(gridDokter.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_gridDokterMouseClicked

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        nama=txtNama.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="SELECT * FROM tabel_dokter WHERE no_dokter='"+ nama +"'";
                st=con.createStatement();
                RsDokter=st.executeQuery(sql);
                while (RsDokter.next()) {
                   cmbPoli.setSelectedItem(RsDokter.getString("nama_poli"));
                   txtNama.setText(RsDokter.getString("nama_pasien"));
                   txtAlamat.setText(RsDokter.getString("alamat_pasien"));
                   txtHp.setText(RsDokter.getString("no_hp"));
                   txtJasa.setText(RsDokter.getString("jasa_dokter"));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan");
                   butTambah.setEnabled(false);
                   butSimpan.setEnabled(false);
                   butHapus.setEnabled(true);
                   txtNama.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data TIDAK DITEMUKAN \n"+e.getMessage());
                txtNama.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNamaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftardokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftardokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftardokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftardokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftardokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butHapus;
    private javax.swing.JButton butKembali;
    private javax.swing.JButton butSimpan;
    private javax.swing.JButton butTambah;
    private javax.swing.JComboBox<String> cmbPoli;
    private javax.swing.JTable gridDokter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtJasa;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
