/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicApp;

import javax.swing.JOptionPane;

/**
 *
 * @author Laili
 */
public class masuk extends javax.swing.JFrame {

    /**
     * Creates new form masuk
     */
    public masuk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        butLogin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Silahkan Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 450, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/password.png"))); // NOI18N
        jLabel2.setText("Password ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 106, 90, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/username.png"))); // NOI18N
        jLabel3.setText("Username ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 30));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 52, 240, 30));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 30));

        butLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        butLogin.setText("Login");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });
        jPanel2.add(butLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 450, 250));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.add(jPanel6);

        jPanel3.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));

        jPanel8.setBackground(new java.awt.Color(0, 0, 204));
        jPanel7.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));

        jPanel10.setBackground(new java.awt.Color(0, 0, 204));
        jPanel9.add(jPanel10);

        jPanel7.add(jPanel9);

        jPanel3.add(jPanel7);

        jPanel11.setBackground(new java.awt.Color(0, 0, 204));

        jPanel12.setBackground(new java.awt.Color(0, 0, 204));
        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 0, 204));

        jPanel14.setBackground(new java.awt.Color(0, 0, 204));
        jPanel13.add(jPanel14);

        jPanel11.add(jPanel13);

        jPanel15.setBackground(new java.awt.Color(0, 0, 204));

        jPanel16.setBackground(new java.awt.Color(0, 0, 204));
        jPanel15.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(0, 0, 204));

        jPanel18.setBackground(new java.awt.Color(0, 0, 204));
        jPanel17.add(jPanel18);

        jPanel15.add(jPanel17);

        jPanel11.add(jPanel15);

        jPanel3.add(jPanel11);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 570));

        jPanel19.setBackground(new java.awt.Color(0, 0, 204));

        jPanel20.setBackground(new java.awt.Color(0, 0, 204));
        jPanel19.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(0, 0, 204));

        jPanel22.setBackground(new java.awt.Color(0, 0, 204));
        jPanel21.add(jPanel22);

        jPanel19.add(jPanel21);

        jPanel23.setBackground(new java.awt.Color(0, 0, 204));

        jPanel24.setBackground(new java.awt.Color(0, 0, 204));
        jPanel23.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(0, 0, 204));

        jPanel26.setBackground(new java.awt.Color(0, 0, 204));
        jPanel25.add(jPanel26);

        jPanel23.add(jPanel25);

        jPanel19.add(jPanel23);

        jPanel27.setBackground(new java.awt.Color(0, 0, 204));

        jPanel28.setBackground(new java.awt.Color(0, 0, 204));
        jPanel27.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(0, 0, 204));

        jPanel30.setBackground(new java.awt.Color(0, 0, 204));
        jPanel29.add(jPanel30);

        jPanel27.add(jPanel29);

        jPanel31.setBackground(new java.awt.Color(0, 0, 204));

        jPanel32.setBackground(new java.awt.Color(0, 0, 204));
        jPanel31.add(jPanel32);

        jPanel33.setBackground(new java.awt.Color(0, 0, 204));

        jPanel34.setBackground(new java.awt.Color(0, 0, 204));
        jPanel33.add(jPanel34);

        jPanel31.add(jPanel33);

        jPanel27.add(jPanel31);

        jPanel19.add(jPanel27);

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 10, 570));

        jPanel35.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1100, -1));

        jPanel36.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 1100, -1));

        jPanel41.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 450, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        // TODO add your handling code here:
        if (txtUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Username!");
            txtUsername.requestFocus();
        }
        else if (txtPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Password!");
            txtPassword.requestFocus();
        }
        else if(txtUsername.getText().contains("adminklinik") && txtPassword.getText().contains("helgiklinik1")) {
            new beranda().show();
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Username atau Password salah");
        }

    }//GEN-LAST:event_butLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
