package clinicApp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class pasien extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsPasien;
private String sql="";
public static int statusSearcing = 0;

private String noreg,nama,alamat,tempatlhr,jkelamin,nohp;

    public pasien() {
        initComponents();
        contabel();
        showdata("SELECT * FROM tabel_pasien");
    }

    private void form_awal(){
        form_disable();
        form_clear(); 
        butSimpan.setText("Simpan");
        butTambah.requestFocus(true);
        butSimpan.setEnabled(false); //memungkinkan untuk mengaktifkan button simpan? salah
        butBatal.setEnabled(false);
        butHapus.setEnabled(false);
        butEdit.setEnabled(false);
    }
    
    private void form_disable(){
        txtNoreg.setEnabled(false);
        txtNama.setEnabled(false);
        txtAlamat.setEnabled(false);
        txtTempat.setEnabled(false);
        txtHp.setEnabled(false);
        cmbKelamin.setEnabled(false);
  }
    
    private void form_enable(){
        txtNoreg.setEnabled(true);
        txtNama.setEnabled(true);
        txtAlamat.setEnabled(true);
        txtTempat.setEnabled(true);
        txtHp.setEnabled(true);
        cmbKelamin.setEnabled(true);
  }
    
    private void form_clear(){
       txtNoreg.setText(""); //menerapkan teks sesuai ""
       txtNama.setText("");
       txtAlamat.setText("");
       txtTempat.setText("");
       txtHp.setText("");
       cmbKelamin.setSelectedItem("Pilih");
      }
    
    private void contabel (){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_klinikhelgi", "root", "");
            } catch (Exception e) {
            System.out.println("GAGAL Terkoneksi Dengan Database\n"+e);
        }
    }
    
    private void showdata(String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No. Reg");
        datalist.addColumn("Nama");
        datalist.addColumn("Alamat");
        datalist.addColumn("Tempat Lahir");
        datalist.addColumn("Tanggal Lahir");
        datalist.addColumn("Jenis Kelamin");
        datalist.addColumn("No. HP");
       try {
            st=con.createStatement();
            RsPasien=st.executeQuery("SELECT * FROM tabel_pasien");
            while (RsPasien.next()){
                datalist.addRow(new Object[]{
                    RsPasien.getString(1), RsPasien.getString(2), 
                    RsPasien.getString(3), RsPasien.getString(4), RsPasien.getString(5), 
                    RsPasien.getString(6), RsPasien.getString(7)
                });
                gridPasien.setModel(datalist);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Ditampilkan \n"+e.getMessage());
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNoreg = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        cmbKelamin = new javax.swing.JComboBox<>();
        txtHp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridPasien = new javax.swing.JTable();
        butSimpan = new javax.swing.JButton();
        butEdit = new javax.swing.JButton();
        butHapus = new javax.swing.JButton();
        butBatal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        butTambah = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        butCari = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        butKeluar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jDlahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("No. Registrasi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        txtNoreg.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtNoreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoregActionPerformed(evt);
            }
        });
        txtNoreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoregKeyPressed(evt);
            }
        });
        jPanel1.add(txtNoreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 310, -1));

        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 310, -1));

        txtAlamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 310, -1));

        txtTempat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatActionPerformed(evt);
            }
        });
        jPanel1.add(txtTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 310, -1));

        cmbKelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Laki-Laki", "Perempuan" }));
        cmbKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelaminActionPerformed(evt);
            }
        });
        jPanel1.add(cmbKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 180, -1));

        txtHp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHpActionPerformed(evt);
            }
        });
        jPanel1.add(txtHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 310, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Tempat Lahir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 80, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Lahir");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 90, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("No. HP");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));

        gridPasien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gridPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Reg", "Nama", "Alamat", "Tempat Lahir", "Tanggal Lahir", "Jenis Kelamin", "No. HP"
            }
        ));
        gridPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridPasien);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 550, 260));

        butSimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        butSimpan.setText(" Simpan");
        butSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(butSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 420, 30));

        butEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/change.png"))); // NOI18N
        butEdit.setText(" Edit");
        butEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEditActionPerformed(evt);
            }
        });
        jPanel1.add(butEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 100, 30));

        butHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        butHapus.setText(" Hapus");
        butHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHapusActionPerformed(evt);
            }
        });
        jPanel1.add(butHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 100, 30));

        butBatal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancel.png"))); // NOI18N
        butBatal.setText(" Batal");
        butBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBatalActionPerformed(evt);
            }
        });
        jPanel1.add(butBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 90, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Form Pendaftaraan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 420, 20));

        butTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        butTambah.setText(" Tambah");
        butTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTambahActionPerformed(evt);
            }
        });
        jPanel1.add(butTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 110, 30));

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 240, 30));

        butCari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        butCari.setText(" Cari");
        butCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCariActionPerformed(evt);
            }
        });
        jPanel1.add(butCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 90, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modern Healthcare Clinic Logodj.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Klinik Helgi");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 220, 50));

        jLabel11.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jLabel11.setText("Mitra Pelayanan Kesehatan Yang Menjamin Kepuasan Pasien");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 90));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 10, 90));

        butKeluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        butKeluar.setText(" Kembali");
        butKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKeluarActionPerformed(evt);
            }
        });
        jPanel3.add(butKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 110, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 110));

        jPanel7.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 10));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));
        jPanel1.add(jDlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHpActionPerformed

    private void butSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSimpanActionPerformed
        String Tanggal;
       
        SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
        Tanggal=format.format(jDlahir.getDate());
        noreg=String.valueOf(txtNoreg.getText());
        nama=String.valueOf(txtNama.getText());
        alamat=String.valueOf(txtAlamat.getText());
        tempatlhr = String.valueOf(txtTempat.getText());
        jkelamin=cmbKelamin.getItemAt(cmbKelamin.getSelectedIndex()).toString();
        nohp=String.valueOf(txtHp.getText());
        try {
            sql="INSERT INTO tabel_pasien(no_reg, " //menambahkan ke tabel pasien
                    + "nama_pasien, "
                    + "alamat_pasien, "
                    + "tempat_lahir, "
                    + "tanggal_lahir, "
                    + "jenis_kelamin, "
                    + "no_hp)VALUES"                   
                    + "('"+ noreg +"',"
                    + "'"+ nama +"',"
                    + "'"+ alamat +"',"
                    + "'"+ tempatlhr +"',"
                    + "'"+ Tanggal +"',"
                    + "'"+ jkelamin +"',"
                    + "'"+ nohp +"')";
            st=con.createStatement();
            st.execute(sql);
            showdata("SELECT * FROM tabel_pasien");
            form_awal();
            JOptionPane.showMessageDialog(null, "Data BERHASIL DISIMPAN");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL DISIMPAN\n"+e.getMessage());
        }
    }//GEN-LAST:event_butSimpanActionPerformed

    private void butKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKeluarActionPerformed
        new beranda().show();
            this.dispose();
    }//GEN-LAST:event_butKeluarActionPerformed

    private void butEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEditActionPerformed
        String Tanggal;
       
        SimpleDateFormat format =new SimpleDateFormat("yyyy-MM-dd");
        Tanggal=format.format(jDlahir.getDate());
        noreg=String.valueOf(txtNoreg.getText());
        nama=String.valueOf(txtNama.getText());
        alamat=String.valueOf(txtAlamat.getText());
        tempatlhr = String.valueOf(txtTempat.getText());
        jkelamin=cmbKelamin.getItemAt(cmbKelamin.getSelectedIndex()).toString();
        nohp=String.valueOf(txtHp.getText());
    try {
            sql ="UPDATE tabel_pasien set nama_pasien= '"+nama+"', "
                        + "alamat_pasien = '"+alamat+"', "
                        + "tempat_lahir = '"+tempatlhr+"', "
                        + "tanggal_lahir = '"+Tanggal+"', "
                        + "jenis_kelamin = '"+jkelamin+"', "
                        + "no_hp = '"+nohp+"' "
                        + "where no_reg ='"+noreg+"'";
            st=con.createStatement();
            st.execute(sql);
            showdata("SELECT * FROM tabel_pasien");
            form_awal();
            JOptionPane.showMessageDialog(null, "Data BERHASIL DIEDIT");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL DIEDIT\n"+e.getMessage());
        }
    }//GEN-LAST:event_butEditActionPerformed

    private void cmbKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKelaminActionPerformed

    private void txtNoregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoregActionPerformed

    private void txtTempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatActionPerformed

    private void butTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTambahActionPerformed
        form_enable();
        butTambah.setEnabled(true);
        butSimpan.setEnabled(true);
        butEdit.setEnabled(true);
        butBatal.setEnabled(true);
        butHapus.setEnabled(true);
        
        txtNoreg.requestFocus(true);
    }//GEN-LAST:event_butTambahActionPerformed
   
    private void butBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBatalActionPerformed
        showdata("SELECT * FROM tabel_pasien");
        form_clear();
        butTambah.setEnabled(true);
        butSimpan.setEnabled(true);
        txtNoreg.requestFocus();
        butHapus.setEnabled(true);
        txtNoreg.setEnabled(true);
    }//GEN-LAST:event_butBatalActionPerformed
   
    private void butHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHapusActionPerformed
        noreg = String.valueOf(txtNoreg.getText());
      
        try {
            sql= "DELETE FROM tabel_pasien WHERE tabel_pasien.no_reg =  '"+noreg+"'";
            st=con.createStatement();
            st.execute(sql);
            showdata("SELECT * FROM tabel_pasien");
            form_awal();
            JOptionPane.showMessageDialog(null,"Data BERHSIL DIHAPUS");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL DIHAPUS\n"+e.getMessage());
        }
    }//GEN-LAST:event_butHapusActionPerformed

    private void txtNoregKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoregKeyPressed
        noreg=txtNoreg.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
            try {
                sql="SELECT * FROM tabel_pasien " + "where no_reg='"+ noreg +"'";
                st=con.createStatement();
                RsPasien=st.executeQuery(sql);
                while (RsPasien.next()) {
                   txtNama.setText(RsPasien.getString("nama_pasien"));
                   txtAlamat.setText(RsPasien.getString("alamat_pasien"));
                   txtTempat.setText(RsPasien.getString("tempat_lahir"));
                   jDlahir.setDate(RsPasien.getDate("tanggal_lahir"));
                   cmbKelamin.setSelectedItem(RsPasien.getString("jenis_kelamin"));
                   txtHp.setText(RsPasien.getString("no_hp"));
                   JOptionPane.showMessageDialog(null, "Data Ditemukan");
                   butTambah.setEnabled(false);
                   butSimpan.setEnabled(false);
                   butHapus.setEnabled(true);
                   txtNoreg.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan \n"+e.getMessage());
                txtNoreg.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNoregKeyPressed

    private void gridPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridPasienMouseClicked
        if (gridPasien.getSelectedRowCount()>-1)
        {
            txtNoreg.setText(gridPasien.getValueAt(gridPasien.getSelectedRow(), 0).toString());
            txtNama.setText(gridPasien.getValueAt(gridPasien.getSelectedRow(), 1).toString());
            txtAlamat.setText(gridPasien.getValueAt(gridPasien.getSelectedRow(), 2).toString());
            txtTempat.setText(gridPasien.getValueAt(gridPasien.getSelectedRow(), 3).toString());
            cmbKelamin.setSelectedItem(gridPasien.getValueAt(gridPasien.getSelectedRow(), 5).toString());
            txtHp.setText(gridPasien.getValueAt(gridPasien.getSelectedRow(), 6).toString()); 
        }
    }//GEN-LAST:event_gridPasienMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void butCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCariActionPerformed
        statusSearcing = 1;
        if(txtCari.getText().isEmpty())
            {statusSearcing = 0;}
        else if(statusSearcing==1){
            DefaultTableModel datalist = new DefaultTableModel();
            datalist.addColumn("No. Reg");
            datalist.addColumn("Nama");
            datalist.addColumn("Alamat");
            datalist.addColumn("Tempat Lahir");
            datalist.addColumn("Tanggal Lahir");
            datalist.addColumn("Jenis Kelamin");
            datalist.addColumn("No. HP");
            
            String cari = txtCari.getText();
       try{
            String sql = ("SELECT * FROM tabel_pasien WHERE no_reg LIKE '"+cari+"%'"
                    + "OR nama_pasien like '"+cari+"%'"
                    + "OR no_hp like '"+cari+"%' ORDER BY no_reg");
            st=con.createStatement();
            RsPasien = st.executeQuery(sql);
            while (RsPasien.next()){
                datalist.addRow(new Object[]{
                    RsPasien.getString(1), RsPasien.getString(2),RsPasien.getString(3),
                    RsPasien.getString(4), RsPasien.getString(5),RsPasien.getString(6),
                    RsPasien.getString(7)
                });
            }
            gridPasien.setModel(datalist);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data BELUM TERDAFTAR\n"+e.getMessage());
        } 
        }
    }//GEN-LAST:event_butCariActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased

    }//GEN-LAST:event_txtCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBatal;
    private javax.swing.JButton butCari;
    private javax.swing.JButton butEdit;
    private javax.swing.JButton butHapus;
    private javax.swing.JButton butKeluar;
    private javax.swing.JButton butSimpan;
    private javax.swing.JButton butTambah;
    private javax.swing.JComboBox<String> cmbKelamin;
    private javax.swing.JTable gridPasien;
    private com.toedter.calendar.JDateChooser jDlahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHp;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoreg;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables

    
}
