/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicApp;

import java.sql.Connection;
import connectJ.Koneksi;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laili
 */
public class riwayatpasien extends javax.swing.JFrame {
    private Connection con;
    private Statement st;
    private String sql="";
    private ResultSet RsRiwayat;
    public static int statusSearcing = 0;

    /**
     * Creates new form riwayatpasien
     */
    public riwayatpasien() {
        initComponents();
        showdata();
    }
    
    public void showdata(){ //Untuk menampilkan data dari database
       DefaultTableModel datalist = new DefaultTableModel(); //untuk tabel
       datalist.addColumn("No. Reg"); //kolom pada tabel
       datalist.addColumn("Tanggal Periksa");
       datalist.addColumn("Nama Pasien");
       datalist.addColumn("Alamat");
       datalist.addColumn("No. Hp");
       datalist.addColumn("Poli");
       datalist.addColumn("Nama Dokter");
       datalist.addColumn("Diagnosis");
       datalist.addColumn("Obat");
       datalist.addColumn("Total Harga");
       datalist.addColumn("Item Obat");
       datalist.addColumn("Tagihan");
       datalist.addColumn("Bayar");
       datalist.addColumn("Kembalian");
       try{
            con=Koneksi.getCon();
            st=con.createStatement();
            RsRiwayat=st.executeQuery("SELECT * FROM tabel_checkup");
            while (RsRiwayat.next()){
                datalist.addRow(new Object[]{
                    RsRiwayat.getString(1), RsRiwayat.getString(2), 
                    RsRiwayat.getString(3), RsRiwayat.getString(4), RsRiwayat.getString(5), 
                    RsRiwayat.getString(6), RsRiwayat.getString(7), RsRiwayat.getString(8), 
                    RsRiwayat.getString(9),RsRiwayat.getString(12), RsRiwayat.getString(13), RsRiwayat.getString(14), 
                    RsRiwayat.getString(15), RsRiwayat.getString(16)
                });
                gridRiwayat.setModel(datalist);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Ditampilkan \n"+e.getMessage());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butKembali = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridRiwayat = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        butCari = new javax.swing.JButton();
        butRefresh = new javax.swing.JButton();
        butHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Modern Healthcare Clinic Logodj.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Klinik Helgi");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 2, 14)); // NOI18N
        jLabel3.setText("Mitra Pelayanan Kesehatan Yang Menjamin Kepuasan Pasien");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        butKembali.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        butKembali.setText(" Kembali");
        butKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKembaliActionPerformed(evt);
            }
        });
        jPanel3.add(butKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1100, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 90));

        jPanel6.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1120, 10));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Riwayat Kunjungan Pasien");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 260, 10));

        gridRiwayat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gridRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Reg", "Tanggal Periksa", "Nama Pasien", "Alamat", "No. Hp", "Poli", "Nama Dokter", "Diagnosis", "Obat", "Harga", "Jumlah Obat", "Total Harga", "Item", "Tagihan", "Bayar", "Kembalian"
            }
        ));
        gridRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridRiwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridRiwayat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 1010, 250));

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 270, 30));

        butCari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        butCari.setText(" Cari");
        butCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCariActionPerformed(evt);
            }
        });
        jPanel1.add(butCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, 30));

        butRefresh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/fresh.png"))); // NOI18N
        butRefresh.setText(" Refresh");
        butRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(butRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 250, -1, 30));

        butHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        butHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        butHapus.setText("Hapus");
        butHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHapusActionPerformed(evt);
            }
        });
        jPanel1.add(butHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKembaliActionPerformed
        new beranda().show();
            this.dispose();
    }//GEN-LAST:event_butKembaliActionPerformed

    private void butCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCariActionPerformed
        statusSearcing = 1;
        if(txtCari.getText().isEmpty())
            {statusSearcing = 0;}
        else if(statusSearcing==1){
            DefaultTableModel datalist = new DefaultTableModel();
            datalist.addColumn("No. Reg");
            datalist.addColumn("Tanggal Periksa");
            datalist.addColumn("Nama Pasien");
            datalist.addColumn("Alamat");
            datalist.addColumn("No. Hp");
            datalist.addColumn("Poli");
            datalist.addColumn("Nama Dokter");
            datalist.addColumn("Diagnosis");
            datalist.addColumn("Obat");
            datalist.addColumn("Harga Obat");
            datalist.addColumn("Jumlah Obat");
            datalist.addColumn("Total Harga");
            datalist.addColumn("Item Obat");
            datalist.addColumn("Tagihan");
            datalist.addColumn("Bayar");
            datalist.addColumn("Kembalian");
            
            String cari = txtCari.getText();
       try{
            sql = ("SELECT * FROM tabel_checkup WHERE no_reg LIKE '"+cari+"%'"
                    + "OR nama_pasien like '"+cari+"%'"
                    + "OR no_hp like '"+cari+"%' ORDER BY no_reg");
            st=con.createStatement();
            RsRiwayat = st.executeQuery(sql);
            while (RsRiwayat.next()){
                datalist.addRow(new Object[]{
                    RsRiwayat.getString(1), RsRiwayat.getString(2),RsRiwayat.getString(3),
                    RsRiwayat.getString(4), RsRiwayat.getString(5),RsRiwayat.getString(6),
                    RsRiwayat.getString(7), RsRiwayat.getString(8),RsRiwayat.getString(9),
                    RsRiwayat.getString(10), RsRiwayat.getString(11),RsRiwayat.getString(12),
                    RsRiwayat.getString(13), RsRiwayat.getString(14),RsRiwayat.getString(15),
                    RsRiwayat.getString(16)
                });
            }
            gridRiwayat.setModel(datalist);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "TIDAK ADA DATA yang Tersedia\n"+e.getMessage());
        } 
        }
    }//GEN-LAST:event_butCariActionPerformed

    private void butRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRefreshActionPerformed
        showdata();
        txtCari.setText("");
    }//GEN-LAST:event_butRefreshActionPerformed

    private void butHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHapusActionPerformed
        String noreg = String.valueOf(txtCari.getText());
      
        try {
            sql= "DELETE FROM tabel_checkup WHERE tabel_checkup.no_reg =  '"+noreg+"'";
            st=con.createStatement();
            st.execute(sql);
            showdata();
            JOptionPane.showMessageDialog(null,"Data BERHSIL DIHAPUS");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data GAGAL DIHAPUS\n"+e.getMessage());
        }
        txtCari.setText("");
    }//GEN-LAST:event_butHapusActionPerformed

    private void gridRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridRiwayatMouseClicked
        if (gridRiwayat.getSelectedRowCount()>-1){
            txtCari.setText(gridRiwayat.getValueAt(gridRiwayat.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_gridRiwayatMouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
    
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(riwayatpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(riwayatpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(riwayatpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(riwayatpasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new riwayatpasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCari;
    private javax.swing.JButton butHapus;
    private javax.swing.JButton butKembali;
    private javax.swing.JButton butRefresh;
    private javax.swing.JTable gridRiwayat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
